### ISSUE TITLE
[Feature request] Supports PDF generation

### ISSUE THREAD

**Issue by emisjerry** [HeekangPark/obsidian-hk-code-block#1]
Hi,

Nice work. But i found that all the features all gone when generating PDF.
It would be better if these code block features can be shown in PDF.

Thanks.

**Comment by HeekangPark** [comment]
Thank you for your request.

It seems like default PDF conversion converts notes to PDFs directly from markdown, not from (converted) HTML. I think there might be a PDF conversion plugin that converts markdown to HTML, then re-converts it to PDF. With such plugin, my plugin features might be shown in PDF.

However, I'm afraid your request is little away from my plugin's concept. PDF has fixed width and cannot has horizontal scrollbars, but line numbers and line highlighting features are working only if every line of code blocks are in a single line—that is, if a certain line is too long, the code block should show the horizontal scrollbar and keep it as a single line, not wrapping it to multiple lines. I think converting notes to HTML is better, if you are planning to use my plugin while exporting, rather than PDF.

It's my first Obsidian plugin and I'm still learning Obsidian, so please let me know if there are awesome methods to make your request work.

**Comment by emisjerry** [comment]
I understand. I will get back to you if I find another solution.

**Comment by WayneYam** [comment]
Can you check out the Code Block Enhancer plugin, I think it supports PDF generation.
